export const tradingConfig = {
  tradingMode: process.env.TRADING_MODE || "live",
  symbol: process.env.SYMBOL || "BTCUSDT",
  usdAmount: Number(process.env.USD_AMOUNT || 120),
  reconnectDelayMs: Number(process.env.WS_RECONNECT_DELAY_MS || 2000),
  defaultUsdtBrl: Number(process.env.DEFAULT_USDT_BRL || 5),
  paperStartBalance: Number(process.env.PAPER_START_BALANCE || 1000),
  paperFeeRate: Number(process.env.PAPER_FEE_RATE || 0.0004),
  monitoringSnapshotIntervalMs: Number(
    process.env.MONITORING_SNAPSHOT_INTERVAL_MS || 5000
  ),
  candleInterval: process.env.CANDLE_INTERVAL || "5m",
  candleLimit: Number(process.env.CANDLE_LIMIT || 250),
  analysisIntervalMs: Number(process.env.ANALYSIS_INTERVAL_MS || 15000),
  cooldownMs: Number(process.env.COOLDOWN_MS || 300000),
  orderBookLevels: Number(process.env.ORDER_BOOK_LEVELS || 20),
  fastEmaPeriod: Number(process.env.FAST_EMA_PERIOD || 9),
  slowEmaPeriod: Number(process.env.SLOW_EMA_PERIOD || 21),
  trendEmaPeriod: Number(process.env.TREND_EMA_PERIOD || 55),
  trendSmaPeriod: Number(process.env.TREND_SMA_PERIOD || 200),
  volumeSmaPeriod: Number(process.env.VOLUME_SMA_PERIOD || 20),
  rsiPeriod: Number(process.env.RSI_PERIOD || 14),
  macdFastPeriod: Number(process.env.MACD_FAST_PERIOD || 12),
  macdSlowPeriod: Number(process.env.MACD_SLOW_PERIOD || 26),
  macdSignalPeriod: Number(process.env.MACD_SIGNAL_PERIOD || 9),
  atrPeriod: Number(process.env.ATR_PERIOD || 14),
  takeProfitAtrMultiple: Number(process.env.TAKE_PROFIT_ATR_MULTIPLE || 2.4),
  stopLossAtrMultiple: Number(process.env.STOP_LOSS_ATR_MULTIPLE || 1.3),
  trailingAtrMultiple: Number(process.env.TRAILING_ATR_MULTIPLE || 1.1),
  minAtrPercent: Number(process.env.MIN_ATR_PERCENT || 0.001),
  maxAtrPercent: Number(process.env.MAX_ATR_PERCENT || 0.025),
  minVolumeRatio: Number(process.env.MIN_VOLUME_RATIO || 1.1),
  minCandleBodyRatio: Number(process.env.MIN_CANDLE_BODY_RATIO || 0.55),
  minOrderBookImbalance: Number(process.env.MIN_ORDER_BOOK_IMBALANCE || 0.08),
  longRsiMin: Number(process.env.LONG_RSI_MIN || 55),
  longRsiMax: Number(process.env.LONG_RSI_MAX || 68),
  shortRsiMin: Number(process.env.SHORT_RSI_MIN || 32),
  shortRsiMax: Number(process.env.SHORT_RSI_MAX || 45),
  minLongScore: Number(process.env.MIN_LONG_SCORE || 5),
  minShortScore: Number(process.env.MIN_SHORT_SCORE || 5),
  minScoreGap: Number(process.env.MIN_SCORE_GAP || 1),
  stateSyncIntervalMs: Number(process.env.STATE_SYNC_INTERVAL_MS || 60000),
  backtestLimit: Number(process.env.BACKTEST_LIMIT || 1000),
  backtestInitialBalance: Number(process.env.BACKTEST_INITIAL_BALANCE || 1000),
};
